# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('initiative', models.IntegerField()),
                ('armor_class', models.IntegerField()),
                ('fortitude', models.IntegerField()),
                ('reflex', models.IntegerField()),
                ('will', models.IntegerField()),
                ('hit_points', models.IntegerField()),
                ('damage_taken', models.IntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('character_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='initiative.Character')),
                ('count', models.IntegerField(default=0)),
            ],
            bases=('initiative.character',),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('character_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='initiative.Character')),
                ('present', models.BooleanField(default=True)),
            ],
            bases=('initiative.character',),
        ),
    ]
