# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('initiative', models.IntegerField()),
                ('armor_class', models.IntegerField()),
                ('fortitude', models.IntegerField()),
                ('reflex', models.IntegerField()),
                ('will', models.IntegerField()),
                ('hit_points', models.IntegerField()),
                ('notes', models.CharField(max_length=200)),
            ],
        ),
    ]
