# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiative', '0002_auto_20170501_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='damage_taken',
            field=models.IntegerField(default=0),
        ),
    ]
