# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initiative', '0002_monster_initiative_rolls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moster_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiative', models.IntegerField(default=0)),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiative.Monster')),
            ],
        ),
    ]
