# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 22:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initiative', '0003_moster_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Moster_list',
            new_name='MonsterList',
        ),
    ]
