# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiative', '0003_character_damage_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='unique',
            field=models.BooleanField(default=False),
        ),
    ]
