# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-18 00:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initiative', '0004_auto_20170711_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monsterlist',
            old_name='monster',
            new_name='name',
        ),
    ]
