# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiative', '0004_character_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
